# Thông tin dự án
sonar.projectKey=prj1-20252-e15_prj1-20252-e15
sonar.organization=prj1-20252-e15

# Vị trí code cần quét (dấu chấm nghĩa là quét toàn bộ thư mục hiện tại)
sonar.sources=.

# Bỏ qua không quét các thư viện và file cấu hình rác
sonar.exclusions=node_modules/**, .github/**

# Tắt cảnh báo SCM (Git Blame)
sonar.scm.disabled=true

# Khai báo nhánh chính
sonar.branch.name=master
