name: VAmPI DevSecOps pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: #manual workflow trigger

jobs:
  security-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: read # cannot overwrite code
      security-events: write # for Semgrep report
      issues: write          # for ZAP report
      pull-requests: read    # for SonarCloud

    steps:
      - name: code-checkout
        uses: actions/checkout@v4 #git clone to the runner (VM)
        with:
          fetch-depth: 0 #for sonarcloud to recognize code structure

      - name: python-setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' 

      - name: dependancies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: SAST-semgrep
        run: |
          pip install semgrep
          semgrep scan --config "p/default" --error --sarif --output semgrep.sarif

      - name: semgrep-sarif
        uses: github/codeql-action/upload-sarif@v3
        if: always() #always save report
        with:
          sarif_file: semgrep.sarif

      - name: SAST-sonarcloud
        # nosemgrep
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: -Dsonar.projectKey=elysiaclisee_VAmPI -Dsonar.organization=elysiaclisee -Dsonar.sources=.
          projectBaseDir: .

      - name: SCA
        run: |
          pip install pip-audit
          pip-audit -r requirements.txt

      - name: VAmPI-backstart
        run: |
          python app.py &
          sleep 15 

      - name: DAST-zap
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:5000' 
          fail_action: true #quality gate
          artifact_name: zap-scan

      - name: zapreport
        uses: actions/upload-artifact@v4
        if: always() 
        with:
          name: zapreport
          path: report_html.html
